### ISSUE TITLE
Exception Handling of Numerical Errors in Controller Main Loop

### ISSUE THREAD

**Issue by mschottdorf** [CohenLabPrinceton/Ventilator-Dev#44]
Jonny suggested that the controller should be able to swallow numerical errors via exception handling in the main loop. 
To make this reality, we should have a dedicated space to collect ideas what this practically means. Are numerical errors to be ignored (i.e. continue with last reasonable value), or smoothed out (clip into reasonable range), and how do we handle alarms?

**Comment by sneakers-the-rat** [comment]
I feel like we should have some sort of temporal threshold for last reading that if we don't get them in that time we throw an alarm. Seems like that could be different for different values, and since we have some parameterization of values now we could set that there. Don't know the details of the controller to address the subtleties of the considerations we need to make.
